# Generated by Django 4.1.3 on 2023-01-09 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeservice_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='take_appointment',
            old_name='worker',
            new_name='user',
        ),
    ]
